// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/calculator-keypad/Current.tsx": () => import("../components/mockups/calculator-keypad/Current.tsx"),
  "./components/mockups/calculator-keypad/ReferenceMatched.tsx": () => import("../components/mockups/calculator-keypad/ReferenceMatched.tsx")
};
