// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/add-party/Current.tsx": () => import("../components/mockups/add-party/Current.tsx"),
  "./components/mockups/add-party/Redesigned.tsx": () => import("../components/mockups/add-party/Redesigned.tsx"),
  "./components/mockups/calculator-keypad/AfterHours.tsx": () => import("../components/mockups/calculator-keypad/AfterHours.tsx"),
  "./components/mockups/calculator-keypad/Current.tsx": () => import("../components/mockups/calculator-keypad/Current.tsx"),
  "./components/mockups/calculator-keypad/ReferenceMatched.tsx": () => import("../components/mockups/calculator-keypad/ReferenceMatched.tsx"),
  "./components/mockups/party-ledger-list/Carded.tsx": () => import("../components/mockups/party-ledger-list/Carded.tsx"),
  "./components/mockups/party-ledger-list/Current.tsx": () => import("../components/mockups/party-ledger-list/Current.tsx")
};
