import { useEffect, useRef } from 'react';

const LONG_PRESS_DELAY_MS = 550;

interface LongPressPartyNameProps {
  name: string;
  canRename: boolean;
  onClick: () => void;
  onLongPress: () => void;
}

export function LongPressPartyName({
  name,
  canRename,
  onClick,
  onLongPress,
}: LongPressPartyNameProps) {
  const timerRef = useRef<number | null>(null);
  const longPressFiredRef = useRef(false);

  const clearTimer = () => {
    if (timerRef.current !== null) {
      window.clearTimeout(timerRef.current);
      timerRef.current = null;
    }
  };

  useEffect(() => clearTimer, []);

  const startLongPress = (event: React.PointerEvent<HTMLButtonElement>) => {
    if (!canRename || (event.pointerType === 'mouse' && event.button !== 0)) return;

    clearTimer();
    longPressFiredRef.current = false;
    timerRef.current = window.setTimeout(() => {
      timerRef.current = null;
      longPressFiredRef.current = true;
      onLongPress();
    }, LONG_PRESS_DELAY_MS);
  };

  const finishPointer = () => {
    clearTimer();
    if (longPressFiredRef.current) {
      // Allow the click generated by this same long-press gesture to be
      // suppressed before resetting for the next interaction.
      window.setTimeout(() => {
        longPressFiredRef.current = false;
      }, 0);
    }
  };

  return (
    <button
      type="button"
      className="block min-w-0 max-w-full text-left font-bold text-[15px] leading-snug text-slate-900 whitespace-normal break-words [overflow-wrap:anywhere] select-none touch-pan-y"
      title={canRename ? 'নাম বদলাতে চেপে ধরুন' : undefined}
      onPointerDown={startLongPress}
      onPointerUp={finishPointer}
      onPointerCancel={finishPointer}
      onPointerLeave={finishPointer}
      onContextMenu={(event) => {
        if (!canRename) return;
        event.preventDefault();
        event.stopPropagation();
        if (!longPressFiredRef.current) {
          longPressFiredRef.current = true;
          onLongPress();
          window.setTimeout(() => {
            longPressFiredRef.current = false;
          }, 0);
        }
      }}
      onKeyDown={(event) => {
        if (canRename && event.key === 'F2') {
          event.preventDefault();
          event.stopPropagation();
          onLongPress();
        }
      }}
      onClick={(event) => {
        event.stopPropagation();
        if (longPressFiredRef.current) {
          event.preventDefault();
          longPressFiredRef.current = false;
          return;
        }
        onClick();
      }}
    >
      {name}
    </button>
  );
}
